spring.application.name=db-arena

spring.datasource.url=jdbc:postgresql://localhost:5432/db-arena
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.socket=DEBUG

spring.jpa.hibernate.ddl-auto=update

jwt.secret=testKey
jwt.expiration=100000000